# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for building the AutoSocial AI agent macOS .app bundle.

Produces a macOS .app bundle (onedir mode):
  - dist/AutoSocialAgent.app  -> macOS app bundle
  - connects to production backend (agents.zettalgor.com) by default
  - reads agent_config.txt next to the .app to override URLs (dev/local)

The agent reads AGENT_TOKEN from:
  1. Environment variable (auto-start mode)
  2. agent_config.txt placed next to the .app
  3. Interactive login prompt (asks email/password)

Usage (from Marketing-backend/):
    .venv/bin/python -m PyInstaller agent_build_mac.spec --clean --noconfirm

Output:
    dist/AutoSocialAgent.app   (macOS app bundle)

Then build the .dmg with build_agent_mac.sh:
    ./build_agent_mac.sh
"""

import os
import sys
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

# Project root (the folder containing this spec file)
PROJECT_ROOT = os.path.abspath(SPECPATH)

# ── Hidden imports ──────────────────────────────────────────────────
hiddenimports = [
    "selenium",
    "selenium.webdriver",
    "selenium.webdriver.chrome",
    "selenium.webdriver.chrome.service",
    "selenium.webdriver.chrome.options",
    "urllib3",
    "requests",
    "websockets",
    "PIL",
]

# Collect all submodules from packages that PyInstaller might miss
hiddenimports += collect_submodules("selenium")

# Selenium Manager — needed to auto-download chromedriver in frozen app
hiddenimports += collect_submodules("selenium.webdriver.common.selenium_manager")
hiddenimports += collect_submodules("selenium.webdriver.chrome.service")

# ── Data files ──────────────────────────────────────────────────────
datas = []

# ── Env bootstrap (production URL baked in) ─────────────────────────
env_bootstrap = """
import os
# Auto-generated by agent_build_mac.spec - production build (macOS)
# These are defaults; agent_config.txt next to the .app can override them
# for dev/local testing without rebuilding.
os.environ.setdefault("DJANGO_BASE_URL", "https://agents.zettalgor.com")
os.environ.setdefault("AGENT_WS_URL", "wss://agents.zettalgor.com/ws/agent/")
"""
bootstrap_path = os.path.join(PROJECT_ROOT, "build", "_env_agent.py")
os.makedirs(os.path.dirname(bootstrap_path), exist_ok=True)
with open(bootstrap_path, "w") as f:
    f.write(env_bootstrap)

# ── Analysis ────────────────────────────────────────────────────────
a = Analysis(
    [bootstrap_path, os.path.join(PROJECT_ROOT, "local_agent", "agent.py")],
    pathex=[PROJECT_ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "pandas", "scipy",
              "win32clipboard", "pywinauto", "win32com", "win32gui", "win32con"],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ── macOS .app bundle (onedir mode) ─────────────────────────────────
# EXE produces the Unix executable that COLLECT wraps into the .app.
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="AutoSocialAgent",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,  # keep terminal output so the agent's logs are visible
    disable_windowed_traceback=False,
    target_arch=None,  # universal build; set "arm64" for Apple Silicon only
    codesign_identity=None,
    entitlements_file=None,
)

# COLLECT bundles the executable + dependencies into the .app structure.
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    name="AutoSocialAgent",
)

# BUNDLE wraps the COLLECT output into a proper macOS .app bundle.
# This is what makes dist/AutoSocialAgent.app appear as a real app.
app = BUNDLE(
    coll,
    name="AutoSocialAgent.app",
    icon=None,  # add an .icns path here if you have an app icon
    bundle_identifier="com.zettalgor.autosocialagent",
    info_plist={
        "CFBundleName": "AutoSocialAgent",
        "CFBundleDisplayName": "AutoSocial Agent",
        "CFBundleShortVersionString": "1.0.0",
        "CFBundleVersion": "1.0.0",
        "LSMinimumSystemVersion": "11.0",
        "NSHighResolutionCapable": True,
    },
)