# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for building the AutoSocial AI agent exe.

Produces a SINGLE STANDALONE exe (onefile mode):
  - agent.exe  → one file, no _internal folder needed
  - connects to production backend (agents.zettalgor.com) by default
  - reads agent_config.txt next to the exe to override URLs (dev/local)

The exe reads AGENT_TOKEN from:
  1. Environment variable (auto-start mode)
  2. agent_config.txt placed next to the exe
  3. Interactive login prompt (asks email/password)

Usage:
    .venv\\Scripts\\python.exe -m PyInstaller agent_build.spec --clean --noconfirm

Output:
    dist\\agent.exe   (single standalone file)
"""

import os
import sys
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

# Project root (the folder containing this spec file)
PROJECT_ROOT = os.path.abspath(SPECPATH)

# ── Hidden imports ──────────────────────────────────────────────────
# Playwright replaces Selenium — no ChromeDriver needed.
hiddenimports = [
    "playwright",
    "playwright.sync_api",
    "playwright.async_api",
    "playwright._impl",
    "urllib3",
    "requests",
    "websockets",
    "PIL",
    "win32clipboard",
    "pywinauto",
    "psutil",
]

# Collect all Playwright submodules so PyInstaller bundles them.
hiddenimports += collect_submodules("playwright")

# Only include the pywinauto Windows modules actually used by the upload helper.
hiddenimports += [
    "pywinauto",
    "pywinauto.findwindows",
    "pywinauto.keyboard",
    "pywinauto.mouse",
    "pywinauto.win32functions",
    "pywinauto.win32structures",
    "pywinauto.controls.common_controls",
    "pywinauto.controls.hwndwrapper",
]

# ── Collect automation engine ──────────────────────────────────────
hiddenimports += collect_submodules("core.automation_engine")

# ── Playwright data files (browser binaries, driver) ───────────────
# Playwright stores browser binaries in its own package directory.
# We need to bundle them so the exe can launch Chrome without a separate
# `playwright install` step on the target machine.
playwright_datas = collect_data_files("playwright", include_py_files=False)
datas = playwright_datas

# Also try to find and bundle the Playwright driver (node.js binary).
# This is what actually communicates with Chrome via CDP.
try:
    import playwright
    pw_dir = os.path.dirname(playwright.__file__)
    driver_dir = os.path.join(pw_dir, "driver")
    if os.path.isdir(driver_dir):
        for item in os.listdir(driver_dir):
            item_path = os.path.join(driver_dir, item)
            if os.path.isfile(item_path):
                datas.append((item_path, "playwright/driver"))
            elif os.path.isdir(item_path):
                for root, dirs, files in os.walk(item_path):
                    for f in files:
                        src = os.path.join(root, f)
                        rel = os.path.relpath(root, driver_dir)
                        datas.append((src, os.path.join("playwright/driver", rel)))
except Exception as e:
    print(f"[WARN] Could not bundle Playwright driver: {e}")

# Try to bundle the Chromium browser binary if it was installed.
# Playwright stores browsers in ~/AppData/Local/ms-playwright on Windows.
try:
    browser_cache = os.path.join(
        os.environ.get("LOCALAPPDATA", os.path.expanduser("~")),
        "ms-playwright"
    )
    if os.path.isdir(browser_cache):
        for chromium_dir in os.listdir(browser_cache):
            if "chromium" in chromium_dir.lower():
                src_dir = os.path.join(browser_cache, chromium_dir)
                for root, dirs, files in os.walk(src_dir):
                    for f in files:
                        src = os.path.join(root, f)
                        rel = os.path.relpath(root, src_dir)
                        datas.append((src, os.path.join("ms-playwright", chromium_dir, rel)))
except Exception as e:
    print(f"[WARN] Could not bundle Chromium browser: {e}")

# ── Env bootstrap (production URL baked in) ─────────────────────────
# Production URLs are baked in as DEFAULTS. The agent reads overrides
# from agent_config.txt next to the exe (if present), so the SAME exe
# works for both production and dev without rebuilding.
env_bootstrap = """
import os
import sys
# Auto-generated by agent_build.spec - production build
# These are defaults; agent_config.txt next to the exe can override them
# for dev/local testing without rebuilding.
os.environ.setdefault("DJANGO_BASE_URL", "https://agents.zettalgor.com")
os.environ.setdefault("AGENT_WS_URL", "wss://agents.zettalgor.com/ws/agent/")
# In the frozen exe we use the real `core` package (bundled by PyInstaller).
# The dev-only alias (core -> agent/) is NOT created here; agent.py handles
# that in non-frozen mode only.
"""
bootstrap_path = os.path.join(PROJECT_ROOT, "build", "_env_agent.py")
os.makedirs(os.path.dirname(bootstrap_path), exist_ok=True)
with open(bootstrap_path, "w", encoding="utf-8") as f:
    f.write(env_bootstrap)

# ── Analysis ────────────────────────────────────────────────────────
agent_entry = os.path.join(PROJECT_ROOT, "agent", "local_agent", "agent.py")
if not os.path.exists(agent_entry):
    raise FileNotFoundError(f"Agent entry script not found: {agent_entry}")

a = Analysis(
    [bootstrap_path, agent_entry],
    pathex=[PROJECT_ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "pandas", "scipy", "selenium"],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ── Single standalone exe (onefile mode) ────────────────────────────
# All binaries + data are embedded inside ONE exe file.
# No _internal folder needed — just copy agent.exe to any PC and run.
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name="agent",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)