# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for building the AutoSocial AI agent exe.

Produces a SINGLE STANDALONE exe (onefile mode):
  - agent.exe  → one file, no _internal folder needed
  - connects to production backend (agents.zettalgor.com) by default
  - reads agent_config.txt next to the exe to override URLs (dev/local)

The exe reads AGENT_TOKEN from:
  1. Environment variable (auto-start mode)
  2. agent_config.txt placed next to the exe
  3. Interactive login prompt (asks email/password)

Usage:
    .venv\\Scripts\\python.exe -m PyInstaller agent_build.spec --clean --noconfirm

Output:
    dist\\agent.exe   (single standalone file)
"""

import os
import sys
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

# Project root (the folder containing this spec file)
PROJECT_ROOT = os.path.abspath(SPECPATH)

# ── Hidden imports ──────────────────────────────────────────────────
hiddenimports = [
    "selenium",
    "selenium.webdriver",
    "selenium.webdriver.chrome",
    "selenium.webdriver.chrome.service",
    "selenium.webdriver.chrome.options",
    "urllib3",
    "requests",
    "websockets",
    "PIL",
    "win32clipboard",
    "pywinauto",
]

# Collect all submodules from packages that PyInstaller might miss
hiddenimports += collect_submodules("selenium")

# Only include the pywinauto Windows modules actually used by the upload helper.
# collect_submodules("pywinauto") pulls in Linux test suites and loops forever.
hiddenimports += [
    "pywinauto",
    "pywinauto.findwindows",
    "pywinauto.keyboard",
    "pywinauto.mouse",
    "pywinauto.win32functions",
    "pywinauto.win32structures",
    "pywinauto.controls.common_controls",
    "pywinauto.controls.hwndwrapper",
]

# Selenium Manager — needed to auto-download chromedriver in frozen exe
hiddenimports += collect_submodules("selenium.webdriver.common.selenium_manager")
hiddenimports += collect_submodules("selenium.webdriver.chrome.service")

# ── Collect automation engine ──────────────────────────────────────
# The automation engine code imports modules as `core.automation_engine...`.
# The real package lives at `core/automation_engine/` (with proper __init__.py
# files). Collect all submodules so PyInstaller bundles them.
# In dev mode, agent.py creates a runtime alias `core -> agent/` so the code
# under `agent/automation_engine/` is used. In the frozen exe we use the real
# `core` package directly (no alias needed).
hiddenimports += collect_submodules("core.automation_engine")

# ── Data files ──────────────────────────────────────────────────────
# NOTE: Do NOT bundle agent_config.json — it contains machine-specific
# absolute paths that break on other PCs. The agent creates a fresh
# profile under %LOCALAPPDATA%\AutoSocialAI on first run instead.
datas = []

# ── Env bootstrap (production URL baked in) ─────────────────────────
# Production URLs are baked in as DEFAULTS. The agent reads overrides
# from agent_config.txt next to the exe (if present), so the SAME exe
# works for both production and dev without rebuilding.
env_bootstrap = """
import os
import sys
# Auto-generated by agent_build.spec - production build
# These are defaults; agent_config.txt next to the exe can override them
# for dev/local testing without rebuilding.
os.environ.setdefault("DJANGO_BASE_URL", "https://agents.zettalgor.com")
os.environ.setdefault("AGENT_WS_URL", "wss://agents.zettalgor.com/ws/agent/")
# In the frozen exe we use the real `core` package (bundled by PyInstaller).
# The dev-only alias (core -> agent/) is NOT created here; agent.py handles
# that in non-frozen mode only.
"""
bootstrap_path = os.path.join(PROJECT_ROOT, "build", "_env_agent.py")
os.makedirs(os.path.dirname(bootstrap_path), exist_ok=True)
with open(bootstrap_path, "w", encoding="utf-8") as f:
    f.write(env_bootstrap)

# ── Analysis ────────────────────────────────────────────────────────
agent_entry = os.path.join(PROJECT_ROOT, "agent", "local_agent", "agent.py")
if not os.path.exists(agent_entry):
    raise FileNotFoundError(f"Agent entry script not found: {agent_entry}")

a = Analysis(
    [bootstrap_path, agent_entry],
    pathex=[PROJECT_ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "pandas", "scipy"],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ── Single standalone exe (onefile mode) ────────────────────────────
# All binaries + data are embedded inside ONE exe file.
# No _internal folder needed — just copy agent.exe to any PC and run.
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name="agent",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)